import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../models/surah_info.dart';

const Color kPrimaryColor = Color(0xFF040C23);
const Color gray = Color(0xFF121931);
const Color blue = Color(0XFF2062E3);
const List<Color> kColorList = [
  Color(0x8481a4ce),
  Color(0xb53973b6),
  Color(0x8e1e82f6),
  Color(0x440757b5),
];

Text logoText = Text('آيــات',
    style: GoogleFonts.amiri(
        fontWeight: FontWeight.bold, fontSize: 48, color: Colors.white));

final List<String> texts = [
  'اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ',
  'يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ',
  'وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ',
  ' إِنَّا نَحْنُ نَزَّلْنَا الذِّكْرَ وَإِنَّا لَهُ لَحَافِظُونَ',
  'رَّبِّ ٱغۡفِرۡ لِی وَلِوَ ٰ⁠لِدَیَّ',
  'وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ',
  'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
  'فَقُلْتُ اسْتَغْفِرُوا رَبَّكُمْ إِنَّهُ كَانَ غَفَّارًا',
  'وَلَقَدْ نَعْلَمُ أَنَّكَ يَضِيقُ صَدْرُكَ بِمَا يَقُولُونَ',
  'رَبِّ إِنِّي ظَلَمْتُ نَفْسِي',
  'لَا تَخَافَاۤۖ إِنَّنِی مَعَكُمَاۤ أَسۡمَعُ وَأَرَىٰ ',
];

final List<int> pageNumbers = [
  1,
  2,
  50,
  77,
  106,
  128,
  151,
  177,
  187,
  208,
  221,
  235,
  249,
  255,
  262,
  267,
  282,
  293,
  305,
  312,
  322,
  332,
  342,
  350,
  359,
  367,
  377,
  385,
  396,
  404,
  411,
  415,
  418,
  428,
  434,
  440,
  446,
  453,
  458,
  467,
  477,
  483,
  489,
  496,
  499,
  502,
  507,
  511,
  515,
  518,
  520,
  523,
  526,
  528,
  531,
  534,
  537,
  542,
  545,
  549,
  551,
  553,
  554,
  556,
  558,
  560,
  562,
  564,
  566,
  568,
  570,
  572,
  574,
  575,
  577,
  578,
  580,
  582,
  583,
  585,
  586,
  587,
  587,
  589,
  590,
  591,
  591,
  592,
  593,
  594,
  595,
  595,
  596,
  596,
  597,
  597,
  598,
  598,
  599,
  599,
  600,
  600,
  601,
  601,
  601,
  602,
  602,
  602,
  603,
  603,
  603,
  604,
  604,
  604,
];

List<SurahInfo> quranSurahs = [
  SurahInfo(
    surahNumber: 1,
    arabicName: "الفاتحة",
    numberOfVerses: 7,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 2,
    arabicName: "البقرة",
    numberOfVerses: 286,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 3,
    arabicName: "آل عمران",
    numberOfVerses: 200,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 4,
    arabicName: "النساء",
    numberOfVerses: 176,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 5,
    arabicName: "المائدة",
    numberOfVerses: 120,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 6,
    arabicName: "الأنعام",
    numberOfVerses: 165,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 7,
    arabicName: "الأعراف",
    numberOfVerses: 206,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 8,
    arabicName: "الأنفال",
    numberOfVerses: 75,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 9,
    arabicName: "التوبة",
    numberOfVerses: 129,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 10,
    arabicName: "يونس",
    numberOfVerses: 109,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 11,
    arabicName: "هود",
    numberOfVerses: 123,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 12,
    arabicName: "يوسف",
    numberOfVerses: 111,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 13,
    arabicName: "الرعد",
    numberOfVerses: 43,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 14,
    arabicName: "ابراهيم",
    numberOfVerses: 52,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 15,
    arabicName: "الحجر",
    numberOfVerses: 99,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 16,
    arabicName: "النحل",
    numberOfVerses: 128,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 17,
    arabicName: "الإسراء",
    numberOfVerses: 111,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 18,
    arabicName: "الكهف",
    numberOfVerses: 110,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 19,
    arabicName: "مريم",
    numberOfVerses: 98,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 20,
    arabicName: "طه",
    numberOfVerses: 135,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 21,
    arabicName: "الأنبياء",
    numberOfVerses: 112,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 22,
    arabicName: "الحج",
    numberOfVerses: 78,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 23,
    arabicName: "المؤمنون",
    numberOfVerses: 118,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 24,
    arabicName: "النور",
    numberOfVerses: 64,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 25,
    arabicName: "الفرقان",
    numberOfVerses: 77,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 26,
    arabicName: "الشعراء",
    numberOfVerses: 227,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 27,
    arabicName: "النمل",
    numberOfVerses: 93,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 28,
    arabicName: "القصص",
    numberOfVerses: 88,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 29,
    arabicName: "العنكبوت",
    numberOfVerses: 69,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 30,
    arabicName: "الروم",
    numberOfVerses: 60,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 31,
    arabicName: "لقمان",
    numberOfVerses: 34,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 32,
    arabicName: "السجدة",
    numberOfVerses: 30,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 33,
    arabicName: "الأحزاب",
    numberOfVerses: 73,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 34,
    arabicName: "سبإ",
    numberOfVerses: 54,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 35,
    arabicName: "فاطر",
    numberOfVerses: 45,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 36,
    arabicName: "يس",
    numberOfVerses: 83,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 37,
    arabicName: "الصافات",
    numberOfVerses: 182,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 38,
    arabicName: "ص",
    numberOfVerses: 88,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 39,
    arabicName: "الزمر",
    numberOfVerses: 75,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 40,
    arabicName: "غافر",
    numberOfVerses: 85,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 41,
    arabicName: "فصلت",
    numberOfVerses: 54,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 42,
    arabicName: "الشورى",
    numberOfVerses: 53,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 43,
    arabicName: "الزخرف",
    numberOfVerses: 89,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 44,
    arabicName: "الدخان",
    numberOfVerses: 59,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 45,
    arabicName: "الجاثية",
    numberOfVerses: 37,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 46,
    arabicName: "الأحقاف",
    numberOfVerses: 35,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 47,
    arabicName: "محمد",
    numberOfVerses: 38,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 48,
    arabicName: "الفتح",
    numberOfVerses: 29,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 49,
    arabicName: "الحجرات",
    numberOfVerses: 18,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 50,
    arabicName: "ق",
    numberOfVerses: 45,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 51,
    arabicName: "الذاريات",
    numberOfVerses: 60,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 52,
    arabicName: "الطور",
    numberOfVerses: 49,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 53,
    arabicName: "النجم",
    numberOfVerses: 62,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 54,
    arabicName: "القمر",
    numberOfVerses: 55,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 55,
    arabicName: "الرحمن",
    numberOfVerses: 78,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 56,
    arabicName: "الواقعة",
    numberOfVerses: 96,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 57,
    arabicName: "الحديد",
    numberOfVerses: 29,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 58,
    arabicName: "المجادلة",
    numberOfVerses: 22,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 59,
    arabicName: "الحشر",
    numberOfVerses: 24,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 60,
    arabicName: "الممتحنة",
    numberOfVerses: 13,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 61,
    arabicName: "الصف",
    numberOfVerses: 14,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 62,
    arabicName: "الجمعة",
    numberOfVerses: 11,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 63,
    arabicName: "المنافقون",
    numberOfVerses: 11,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 64,
    arabicName: "التغابن",
    numberOfVerses: 18,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 65,
    arabicName: "الطلاق",
    numberOfVerses: 12,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 66,
    arabicName: "التحريم",
    numberOfVerses: 12,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 67,
    arabicName: "الملك",
    numberOfVerses: 30,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 68,
    arabicName: "القلم",
    numberOfVerses: 52,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 69,
    arabicName: "الحاقة",
    numberOfVerses: 52,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 70,
    arabicName: "المعارج",
    numberOfVerses: 44,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 71,
    arabicName: "نوح",
    numberOfVerses: 28,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 72,
    arabicName: "الجن",
    numberOfVerses: 28,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 73,
    arabicName: "المزمل",
    numberOfVerses: 20,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 74,
    arabicName: "المدثر",
    numberOfVerses: 56,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 75,
    arabicName: "القيامة",
    numberOfVerses: 40,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 76,
    arabicName: "الإنسان",
    numberOfVerses: 31,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 77,
    arabicName: "المرسلات",
    numberOfVerses: 50,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 78,
    arabicName: "النبأ",
    numberOfVerses: 40,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 79,
    arabicName: "النازعات",
    numberOfVerses: 46,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 80,
    arabicName: "عبس",
    numberOfVerses: 42,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 81,
    arabicName: "التكوير",
    numberOfVerses: 29,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 82,
    arabicName: "الإنفطار",
    numberOfVerses: 19,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 83,
    arabicName: "المطففين",
    numberOfVerses: 36,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 84,
    arabicName: "الإنشقاق",
    numberOfVerses: 25,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 85,
    arabicName: "البروج",
    numberOfVerses: 22,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 86,
    arabicName: "الطارق",
    numberOfVerses: 17,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 87,
    arabicName: "الأعلى",
    numberOfVerses: 19,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 88,
    arabicName: "الغاشية",
    numberOfVerses: 26,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 89,
    arabicName: "الفجر",
    numberOfVerses: 30,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 90,
    arabicName: "البلد",
    numberOfVerses: 20,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 91,
    arabicName: "الشمس",
    numberOfVerses: 15,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 92,
    arabicName: "الليل",
    numberOfVerses: 21,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 93,
    arabicName: "الضحى",
    numberOfVerses: 11,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 94,
    arabicName: "الشرح",
    numberOfVerses: 8,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 95,
    arabicName: "التين",
    numberOfVerses: 8,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 96,
    arabicName: "العلق",
    numberOfVerses: 19,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 97,
    arabicName: "القدر",
    numberOfVerses: 5,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 98,
    arabicName: "البينة",
    numberOfVerses: 8,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 99,
    arabicName: "الزلزلة",
    numberOfVerses: 8,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 100,
    arabicName: "العاديات",
    numberOfVerses: 11,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 101,
    arabicName: "القارعة",
    numberOfVerses: 11,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 102,
    arabicName: "التكاثر",
    numberOfVerses: 8,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 103,
    arabicName: "العصر",
    numberOfVerses: 3,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 104,
    arabicName: "الهمزة",
    numberOfVerses: 9,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 105,
    arabicName: "الفيل",
    numberOfVerses: 5,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 106,
    arabicName: "قريش",
    numberOfVerses: 4,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 107,
    arabicName: "الماعون",
    numberOfVerses: 7,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 108,
    arabicName: "الكوثر",
    numberOfVerses: 3,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 109,
    arabicName: "الكافرون",
    numberOfVerses: 6,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 110,
    arabicName: "النصر",
    numberOfVerses: 3,
    revelationType: "Madani",
  ),
  SurahInfo(
    surahNumber: 111,
    arabicName: "المسد",
    numberOfVerses: 5,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 112,
    arabicName: "الإخلاص",
    numberOfVerses: 4,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 113,
    arabicName: "الفلق",
    numberOfVerses: 5,
    revelationType: "Makki",
  ),
  SurahInfo(
    surahNumber: 114,
    arabicName: "الناس",
    numberOfVerses: 6,
    revelationType: "Makki",
  ),
];
